### ISSUE TITLE
Projekt X

### ISSUE THREAD

**Issue by Ksawkx** [2percentsilk/haikus-for-codespaces#73] opened 2021-11-27 16:43 UTC

**Comment by ronnicolasp** [comment] 2021-12-02 00:00
I see as project X as the title says, but haven't seen what project it is because I'm a newcomer wanting more of these features. Are there any other problems? For example: Putting Work First​—Is It Satisfying? Japan, is a country with more advanced technology in the past decades, once their wage earners were often moved to new locations with promotions and salary increases. But more often than not, this meant that the head of the house had to move to another city far from his family. Or like now because of the pandemic and the strong will to work from home with internet facilities is also not an easy thing. We're back in Japan... consider another reason...
Among the reasons the family did not move were: elderly parents, the child's school interruption, and the family's recent purchase of a house. But the results are sometimes tragic: broken homes, divorce, and even suicide. The Mainichi Daily News of the '80s called it an “'Unhealthy' Lifestyle for Corporate Profits.”

The current survey shows that a growing number of workers feel that the company should not be a major concern. Will they put their family first? In fact, there seems to be a tendency among Japanese people to spend more time on personal matters other than family.

That the current lifestyle is not entirely satisfactory is reflected in the record number of suicides in Japan in 1983. In the worst suicide outbreak since records began to be kept in 1947, 25,202 people committed suicide. Nearly half of male suicides are in their 40s and 50s. Appropriately, an editorial in the Mainichi Daily News suggested that “humans must liberate themselves from the way of life governed by the spirit of 'organization'”.
Is the problem solving workable?
While I work remotely, we need to balance studying the Bible with our families, becoming better parents and having a more satisfying home life. While we parents are good providers of success here, we have learned what to come first and, as a result, are enjoying a meaningful life with the prospect of long-term benefits.

**Comment by ronnicolasp** [comment] 2021-12-02 00:03
> I see as project X as the title says, but haven't seen what project it is because I'm a newcomer wanting more of these features. Are there any other problems? For example: Putting Work First​—Is It Satisfying? Japan, is a country with more advanced technology in the past decades, once their wage earners were often moved to new locations with promotions and salary increases. But more often than not, this meant that the head of the house had to move to another city far from his family. Or like now because of the pandemic and the strong will to work from home with internet facilities is also not an easy thing. We're back in Japan... consider another reason... Among the reasons the family did not move were: elderly parents, the child's school interruption, and the family's recent purchase of a house. But the results are sometimes tragic: broken homes, divorce, and even suicide. The Mainichi Daily News of the '80s called it an “'Unhealthy' Lifestyle for Corporate Profits.”
> 
> The current survey shows that a growing number of workers feel that the company should not be a major concern. Will they put their family first? In fact, there seems to be a tendency among Japanese people to spend more time on personal matters other than family.
> 
> That the current lifestyle is not entirely satisfactory is reflected in the record number of suicides in Japan in 1983. In the worst suicide outbreak since records began to be kept in 1947, 25,202 people committed suicide. Nearly half of male suicides are in their 40s and 50s. Appropriately, an editorial in the Mainichi Daily News suggested that “humans must liberate themselves from the way of life governed by the spirit of 'organization'”. Is the problem solving workable? While I work remotely, we need to balance studying the Bible with our families, becoming better parents and having a more satisfying home life. While we parents are good providers of success here, we have learned what to come first and, as a result, are enjoying a meaningful life with the prospect of long-term benefits.

Duplicate of #

**Closed** 2022-01-05 01:30 UTC
